-- =====================================================================
-- V1__init_schema.sql
-- Schema inicial do Task Manager Pro
-- Compatível com H2 (dev) e PostgreSQL (prod).
-- DDL em SQL padrão — evita BIGSERIAL/TIMESTAMPTZ específicos.
-- =====================================================================

-- =====================================================================
-- Tabela: usuarios
-- =====================================================================
CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    senha       VARCHAR(255) NOT NULL,
    nome        VARCHAR(255),
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

-- =====================================================================
-- Tabela: tasks
-- =====================================================================
CREATE TABLE tasks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR(255) NOT NULL,
    description   VARCHAR(255),
    status        VARCHAR(255) NOT NULL DEFAULT 'TODO',
    priority      VARCHAR(255) NOT NULL DEFAULT 'MEDIUM',
    due_date      DATE,
    data_criacao  TIMESTAMP,
    usuario_id    BIGINT NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- =====================================================================
-- Tabela: tags
-- Restrição única (name, usuario_id) — espelha @UniqueConstraint da entity
-- =====================================================================
CREATE TABLE tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    color       VARCHAR(7) DEFAULT '#6c757d',
    usuario_id  BIGINT NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uk_tag_name_usuario UNIQUE (name, usuario_id),
    CONSTRAINT fk_tags_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- =====================================================================
-- Tabela: refresh_tokens
-- =====================================================================
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token       VARCHAR(500) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    usuario_id  BIGINT NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- =====================================================================
-- Tabela de junção: task_tags (ManyToMany Task <-> Tag)
-- =====================================================================
CREATE TABLE task_tags (
    task_id   BIGINT NOT NULL,
    tag_id    BIGINT NOT NULL,
    CONSTRAINT pk_task_tags PRIMARY KEY (task_id, tag_id),
    CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);

-- =====================================================================
-- Índices de leitura (alinhados aos padrões de query do app)
-- =====================================================================
-- Tasks por usuário (consultado em quase toda listagem)
CREATE INDEX idx_tasks_usuario_id ON tasks (usuario_id);
-- Tags por usuário
CREATE INDEX idx_tags_usuario_id ON tags (usuario_id);
-- Refresh tokens por usuário (revogação em logout)
CREATE INDEX idx_refresh_tokens_usuario_id ON refresh_tokens (usuario_id);
-- Tasks por status (filtros do Kanban/Dashboard)
CREATE INDEX idx_tasks_usuario_status ON tasks (usuario_id, status);
-- Tasks por data de vencimento (alertas de atraso)
CREATE INDEX idx_tasks_due_date ON tasks (usuario_id, due_date);
